[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.4.1"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono", "uuid"] }
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
chrono = {version = "0.4.37", features = ["serde"]}
r2d2 = "0.8.10"
dotenvy = "0.15.0"
dotenv = "0.15.0"
serde = {version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
env_logger = "0.11.3"
lazy_static = "1.4.0"
tera = "1.19.1"
uuid = {version = "1.8.0", features = ["v4"]}
cargo-watch = "8.5.2"

[lib]
name = "lib"
path ="src/lib.rs"
