[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.4.1"
cargo-watch = "8.5.2"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15.0"
dotenv = "0.15.0"
serde = {version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
env_logger = "0.11.3"
lazy_static = "1.4.0"
chrono = "0.4.37"
libsql = "0.3.3"
libpq = "*"
tera = "1.19.1"
uuid = "1.8.0"

[lib]
name = "lib"
path ="src/lib.rs"
